<?php

namespace Hris\DataQualityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ValidationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValidationRepository extends EntityRepository
{
}
