<?php

namespace Hris\HelpCentreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChapterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChapterRepository extends EntityRepository
{
}
