<?php

namespace Hris\DashboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DashboardChartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DashboardChartRepository extends EntityRepository
{
}
