<?php

namespace Hris\RecordsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HistoryDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryDateRepository extends EntityRepository
{
}
