parameters:
#    hris_organisationunit.example.class: Hris\OrganisationunitBundle\Example

services:
    hris_organisationunit.configure_menu_listener:
                class: Hris\OrganisationunitBundle\EventListener\ConfigureMenuListener
                tags:
                  - { name: kernel.event_listener, event: hris_organisationunit.menu_configure, method: onMenuConfigure }