<?php

namespace Hris\OrganisationunitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrganisationunitStructureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganisationunitStructureRepository extends EntityRepository
{
}
