<?php

namespace Hris\OrganisationunitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrganisationunitGroupsetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganisationunitGroupsetRepository extends EntityRepository
{
}
