<?php

namespace Hris\IntergrationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DataelementFieldOptionRelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataelementFieldOptionRelationRepository extends EntityRepository
{
}
