<?php

namespace Hris\IntergrationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DHISDataConnectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DHISDataConnectionRepository extends EntityRepository
{
}
