<?php

namespace Hris\IntergrationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TIISEmployeeFieldRelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TIISEmployeeFieldRelationRepository extends EntityRepository
{
}
