<?php

namespace Hris\IndicatorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IndicatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndicatorRepository extends EntityRepository
{
}
