<?php

namespace Hris\FormBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FormFieldMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormFieldMemberRepository extends EntityRepository
{
}
