<?php

namespace Hris\FormBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FormSectionFieldMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormSectionFieldMemberRepository extends EntityRepository
{
}
