<?php

namespace Hris\FormBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RelationalFilterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelationalFilterRepository extends EntityRepository
{
}
