<?php

namespace Hris\FormBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResourceTableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceTableRepository extends EntityRepository
{
}
